# Generated by Django 4.0 on 2022-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.CharField(max_length=16, verbose_name='IPv4 adress or domain')),
                ('continent', models.CharField(max_length=32, verbose_name='Continent name')),
                ('country', models.CharField(max_length=64, verbose_name='Country name')),
                ('region', models.CharField(max_length=64, verbose_name='Region')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip code')),
                ('lattitude', models.CharField(max_length=32, verbose_name='Lattitude')),
                ('longitude', models.CharField(max_length=32, verbose_name='Longitude')),
                ('add_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
