# Generated by Django 4.0 on 2022-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ipv4',
            field=models.CharField(max_length=16, unique=True, verbose_name='IPv4 adress or domain'),
        ),
    ]
